In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/home/patel_zeel/aqmsp/aqmsp_results/ijcai24/fire_nrt_J1V-C2_428742.csv')
df.head(2)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
0,28.61403,79.9570,367.00,0.36,0.58,2022-03-24,705,1,VIIRS,h,2.0NRT,303.35,8.79,D
1,28.79206,79.9635,331.67,0.36,0.57,2022-03-24,705,1,VIIRS,n,2.0NRT,300.91,1.61,D

In [6]:
df.acq_time.value_counts()

acq_time
807     65
750     63
839     39
2002    38
2104    38
729     36
2053    34
2019    32
813     32
756     31
826     28
737     24
2040    24
2014    24
1942    22
2032    20
712     19
718     17
705     17
1955    13
828     13
735     13
845     12
701     10
835      9
2123     9
1945     8
2034     7
2110     7
2021     6
852      5
654      5
2057     5
2116     3
1936     3
659      3
837      2
731      2
1923     2
833      1
858      1
2118     1
748      1
646      1
2106     1
Name: count, dtype: int64

In [8]:
# acq_time has this format:
# 705 -> 07:05:00
# 435 -> 04:35:00
def get_time(x):
    x = str(x)
    if len(x) == 3:
        return "0" + x[0] + ":" + x[1:] + ":00"
    else:
        return x[0:2] + ":" + x[2:] + ":00"
df["date"] = pd.to_datetime(df["acq_date"] + " " + df["acq_time"].apply(lambda x: get_time(x)))
df.head(2)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,date
0,28.61403,79.9570,367.00,0.36,0.58,2022-03-24,705,1,VIIRS,h,2.0NRT,303.35,8.79,D,2022-03-24 07:05:00
1,28.79206,79.9635,331.67,0.36,0.57,2022-03-24,705,1,VIIRS,n,2.0NRT,300.91,1.61,D,2022-03-24 07:05:00

In [15]:
df['count'] = 1
# convert each time-stamp to its nearest hour
df["date"] = df["date"].dt.round("H")
df["date"] = df["date"] + pd.Timedelta('5 hours 30 minutes')
df.head(2)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,date,count
0,28.61403,79.9570,367.00,0.36,0.58,2022-03-24,705,1,VIIRS,h,2.0NRT,303.35,8.79,D,2022-03-24 12:30:00,1
1,28.79206,79.9635,331.67,0.36,0.57,2022-03-24,705,1,VIIRS,n,2.0NRT,300.91,1.61,D,2022-03-24 12:30:00,1